siderolabs/go-blockdevice

- Makefile
- blockdevice/table/gpt/gpt.go
- blockdevice/table/gpt/gpt_test.go
- blockdevice/table/gpt/partition/partition.go
- go.mod
- go.sum
This fixes off-by-one block error in partition size being created.
If requested to create partition of N blocks, library created partition
of N+1 blocks.
Also adds first unit-tests for the GPT (more coming).
> fix: calculate last lba of partition correctly

- blockdevice/blockdevice.go
- blockdevice/table/gpt/gpt.go
- blockdevice/table/gpt/gpt_test.go
There are few other changes in this PR:
* partition numbers are now recalculated on change (and should always be
1..n)
* kernel is notified about partition changes when GPT is written back to
disk (breaking change)
* Delete verifies that partition being deleted actually exists in the
list
* more unit-tests, covering new features as well
> feat: implement 'InsertAt' method to insert partitions at any position

- blockdevice/table/gpt/gpt_test.go
- blockdevice/table/gpt/partition/partition.go
- blockdevice/table/table.go
I had to use name `Label()` as `Name` is already used for the struct
field.
This would allow us to match existing partitions to the new manifest, so
that we can preserve contents of the partition before wiping.
> feat: expose partition name (label)

- blockdevice/table/gpt/gpt.go
- blockdevice/table/table.go
External code is using generic interface, not GPT code directly.
> refactor: expose `InsertAt` method via interface

- blockdevice/blkpg/blkpg.go
- blockdevice/blkpg/blkpg_darwin.go
- blockdevice/blkpg/blkpg_linux.go
- blockdevice/table/gpt/gpt.go
Previous strategy was to drop every kernel partition and replace it with
the new partitions, but this fails when Talos tries to resize ephemeral
partition on boot: other partitions are already mounted, so they can't
be removed from the kernel state.
> fix: sync kernel partition table incrementally

- blockdevice/table/gpt/gpt.go
- blockdevice/table/table.go
This allows to check whether partition got actually resized, and whether
the caller needs to update the partition table.
> feat: return resize status from Resize() function

- blockdevice/blockdevice_linux.go
- blockdevice/cmd/wipe/main.go
Full wipe via zeroing out is really slow and might not fit every use
case. Implement "fast" wipe via zeroing out first 1MB of the disk
(should be enough to erase the GPT) and discarding blocks (TRIM for
SSDs) which might zero out the rest of the disk, but it also plays nice
for SSD to mark all blocks as unused.
> feat: implement "fast" wipe

- blockdevice/util/disks.go
Returns the list of disks with device name, size and model info.
To be used in Sidero and Talos.
> feat: add common method to list available disks using /sys/block

- blockdevice/util/util.go
- blockdevice/util/util_test.go
> fix: correctly build paths for `mmcblk` devices

- blockdevice/util/disks.go
These are not what we can install onto, they appear on RPi4.
> fix: ignore `/dev/ram` devices

- blockdevice/blockdevice_linux.go
- blockdevice/lba/lba_linux.go
- blockdevice/partition/gpt/gpt_test.go
- blockdevice/partition/gpt/header.go
The problem was that partition table was never read from disk, so header
was written uninitialized (with zeroes). That leads to `header.Size`
being zero which in turns leads to panic in `DeserializeCRC` which
doesn't do any bounds checking before accessing the slice.
> fix: blockdevice reset should read partition table from disk

- blockdevice/blockdevice_linux.go
- blockdevice/options.go
The problem is the interaction of udevd and our code managing partition
table: udevd might trigger `BLKRRPART` ioctl concurrently with our code
which tries to sync partition table which leads to a mess.
With `flock(LOCK_EX)` udevd skips `BLKRRPART` syscall.
> feat: add an option to open block device with exclusive flock

- blockdevice/blockdevice.go
- blockdevice/blockdevice_darwin.go
- blockdevice/blockdevice_linux.go
- blockdevice/encryption/encryption.go
- blockdevice/encryption/luks/luks.go
- blockdevice/encryption/luks/luks_test.go
- blockdevice/encryption/luks/options.go
- blockdevice/encryption/provider.go
- blockdevice/filesystem/fs.go
- blockdevice/filesystem/iso9660/superblock.go
- blockdevice/filesystem/luks/doc.go
- blockdevice/filesystem/luks/superblock.go
- blockdevice/filesystem/vfat/superblock.go
- blockdevice/filesystem/xfs/superblock.go
- blockdevice/partition/gpt/partition.go
- blockdevice/probe/probe_test.go
- blockdevice/util/util.go
Fixes: https://github.com/talos-systems/talos/issues/3030
Wrap around `cryptsetup` module and support encrypt, open and close
functions as a start.
> feat: implement luks encryption provider

- blockdevice/encryption/luks/luks.go
I guess that happens when the process ends before `Wait` kicks in.
> fix: properly handle no child processes error from cmd.Wait

- blockdevice/lba/lba.go
- blockdevice/lba/lba_test.go
- blockdevice/partition/gpt/gpt.go
Misaligning partition start leads to sub-optimal I/O performance.
> fix: align partition start to physical sector size

- blockdevice/partition/gpt/gpt.go
Some legacy BIOSes need to see at least one bootable partition in the MBR to attempt to boot from the disk.
> fix: Mark the EFI partition in PMBR as bootable.

- blockdevice/partition/gpt/gpt.go
This reverts commit bec914ffdda42abcfe642bc2cdfc9fcda56a74ee.
This breaks UEFI boot.
> fix: revert mark the EFI partition in PMBR as bootable

- blockdevice/util/disk/disks.go
The order was incorrect so it was never reaching the last two cases.
> fix: properly detect nvme and sd card disk types

- blockdevice/util/disk/disks.go
We show disk type as uppercase in `talosctl disk`, so it may happen that
someone will specify it in uppercase in the matcher as well.
> fix: make disk type matcher parser case insensitive

- blockdevice/encryption/luks/luks.go
- blockdevice/encryption/luks/luks_test.go
- blockdevice/encryption/luks/options.go
Add `xchacha12,aes-adiantum-plain64` and `xchacha20,aes-adiantum-plain64` ciphers.
Expose handles for tweaking `--sector-size` and `--key-size`.
Provide a way to set some of the `--perf` flags.
cc: @sergelogvinov Please let me know if I read the issue you created correctly.
> feat: expose more encryption options in the LUKS module

- blockdevice/lba/lba.go
- blockdevice/lba/lba_linux.go
- blockdevice/lba/lba_test.go
Gather information about minimum/optimal I/O size for the disks and
align partitions to either physical block size or min i/o size,
whichever is bigger.
> feat: align partition to minimum I/O size

- blockdevice/blkpg/blkpg_windows.go
- blockdevice/blockdevice_windows.go
- blockdevice/filesystem/fs.go
- blockdevice/lba/lba_windows.go
Fix Windows compatibility.
Needed to be able to build `talosctl.exe` for Windows.
> Fix Windows compatibility

- blockdevice/blockdevice_darwin.go
- blockdevice/blockdevice_linux.go
- blockdevice/blockdevice_windows.go
- blockdevice/options.go
- blockdevice/probe/probe.go
Fixes: https://github.com/talos-systems/go-blockdevice/issues/44
> feat: make probe always open blockdevices in readonly mode

- blockdevice/probe/probe.go
This was missed out in the previous change.
> fix: also open in readonly mode when running `All` lookup method

- blockdevice/blockdevice_linux.go
Function Open does not return error if gpt partition not found.
Talos uses GPT partition, and function blockdevice.Open return nil error even if it not found GPT partition.
Here, for example, we think that partitions do not exist if error return, but is not. It always (most of the cases) returns nil error.
https://github.com/talos-systems/go-blockdevice/blob/e367f9dc7fa935f11672de0fdc8a89429285a07a/blockdevice/probe/probe.go#L150-L160
> fix: gpt partition not found

- blockdevice/blockdevice_linux.go
This reverts commit d7d4cdd7ac56c82caab19246b5decd59f12195eb.
> fix: revert gpt partition not found

- blockdevice/loopback/loopback.go
- blockdevice/probe/probe.go
- blockdevice/probe/probe_test.go
It fix helps to find non-partition file systems.
Another way of fix #46 
* update tests
* resync partitions when loop device activated
> fix: try to find cdrom disks

- blockdevice/blockdevice_linux.go
- blockdevice/partition/gpt/gpt.go
- blockdevice/partition/gpt/gpt_test.go
Fixes: https://github.com/talos-systems/go-blockdevice/issues/51
> fix: return partition table not exist when trying to read an empty dev

- blockdevice/endianness/endianness.go
- blockdevice/endianness/endianness_test.go
- blockdevice/partition/gpt/header.go
- blockdevice/partition/gpt/partition.go
Use optimized methods for conversion, skip conversion for byte slices
(they don't have endianness).
See also https://github.com/talos-systems/talos/issues/4686
Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
> refactor: simplify middle endian functions

- blockdevice/lba/lba.go
- blockdevice/partition/gpt/gpt.go
- blockdevice/partition/gpt/gpt_test.go
- blockdevice/partition/gpt/header.go
- blockdevice/partition/gpt/partition.go
Remove reads of GPT header by bytes, read whole header in memory.
Use simple versions of functions to encode/decode fields without
allocating any memory. Simplify things by removing functions and
removing failure scenarios.
Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
> refactor: rewrite GPT serialize/deserialize functions

- blockdevice/util/disk/disks.go
- blockdevice/util/disk/disks_test.go
Also add a new matcher type for the disk fullpath which supports `*`
matching.
> feat: read symlink fullpath in block device list function

- .conform.yaml
- Makefile
- blockdevice/probe/probe.go
- blockdevice/probe/probe_test.go
- hack/release.sh
The problem was that device path was used, which skips partition as
filesystem label is searched only on the blockdevices.
Add more tests for probe with filesystem labels.
Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
> fix: lookup filesystem labels on the actual device path

- blockdevice/lba/lba.go
- blockdevice/lba/lba_test.go
- blockdevice/partition/gpt/gpt.go
- blockdevice/partition/gpt/gpt_test.go
- blockdevice/probe/probe.go
- blockdevice/probe/probe_test.go
See e.g. https://www.thomas-krenn.com/en/wiki/Partition_Alignment_detailed_explanation
This is the default used by modern disk partition utilities.
Align partition end as well to the same boundary when the partition is
grown to the maximum size (see
https://github.com/siderolabs/talos/issues/4985).
Fix the problem with `WithSingleResult` which never worked properly (?).
It looks like `probe.All` the way it is designed will never work
properly, as the partition name check is done for the blockdevice as a
whole, while the iteration goes over all partition. This goes unnoticed
because of the way this function is actually used.
Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
> fix: align partition to 1M boundary by default

- blockdevice/blkpg/blkpg_freebsd.go
- blockdevice/blockdevice_freebsd.go
- blockdevice/lba/lba_freebsd.go
This PR adds the same stubs that we use for darwin/windows to freebsd.
Signed-off-by: Spencer Smith <spencer.smith@talos-systems.com>
> feat: add freebsd stubs

- blockdevice/util/disk/disks.go
- blockdevice/util/disk/disks_test.go
This way it will be possible to tell what kind of block device is that.
> feat: make disk utils read subsystem information from the `/sys/block`

- blockdevice/encryption/luks/luks.go
- blockdevice/encryption/luks/luks_test.go
- blockdevice/encryption/luks/token.go
- blockdevice/encryption/provider.go
- blockdevice/encryption/token/token.go
Ecryption provider gets 3 new methods:
- `SetToken` - creates/updates token in the LUKS metadata.
- `ReadToken` - reads token from the LUKS metadata.
- `RemoveToken` - removes token from the LUKS metadata.
Library supports 1 token per 1 keyslot to simplify management. If the key slot is removed it's token is removed too.
> feat: support LUKS token management

- blockdevice/encryption/luks/luks.go
When attached to keyslot it is not possible to add token before adding the key.
Adding the key first might lead losing access to the partition if we get powerloss between writing the key and token update.
> fix: do not attach token to a key slot

- blockdevice/encryption/luks/luks.go
- blockdevice/encryption/luks/luks_test.go
Hello.
This small feature allow to us resize the LUKS partitions.
Talos at first boot resizes partitions if they already formatted. (if i am not mistaken)
It helps in future use encrypted images as image template.
Also I am trying to use this module here https://github.com/sergelogvinov/proxmox-csi-plugin/pull/75
Thanks.
> feat: luks resize

- blockdevice/util/util.go
- blockdevice/util/util_test.go
Hello. small fix.
MDRaid uses `p` betwewn device name and partition number.
Thanks.
> fix: define softraid partition

- blkid/blkdid.go
- blkid/blkid_linux.go
- block/device_linux.go
> fix: don't probe empty CD drives

- blkid/blkid_linux.go
- blkid/blkid_linux_test.go
- blkid/internal/filesystems/ext/ext.go
- blkid/internal/filesystems/iso9660/iso9660.go
- blkid/internal/filesystems/luks/luks.go
- blkid/internal/filesystems/lvm2/lvm2.go
- blkid/internal/filesystems/squashfs/squashfs.go
- blkid/internal/filesystems/swap/swap.go
- blkid/internal/filesystems/talosmeta/talosmeta.go
- blkid/internal/filesystems/vfat/vfat.go
- blkid/internal/filesystems/xfs/xfs.go
- blkid/internal/filesystems/zfs/zfs.go
- blkid/internal/partitions/gpt/gpt.go
- blkid/internal/utils/utils.go
- blkid/probe_linux.go
It's not guaranteed that any `.Read` call will read the full buffer.
> fix: use read full when reading data

- block/device_linux.go
Without them, when we pass the result of Fd() into unix.Syscall, Go runtime is free to call finalizer set in os.newFile. More info [here](https://github.com/golang/go/issues/34810).
The proper fix is to either:
1. Use unix.Open/unix.Close as descriptors (ints) everywhere in the Device code. This should hide fd's from Go runtime.
2. Use os.File.SyscallConn().Control which guarantees that descriptor survives. This will also do not put fd's into the blocking mode.
Otherwise, even with os.File.Close it's not guaranteed that runtime.SetFinalizer will not come for `os.File.file`.
> fix: add `runtime.KeepAlive` to keep alive descriptors

- block/device.go
- block/device_linux.go
- block/wipe_linux.go
- block/wipe_linux_test.go
- partitioning/gpt/gpt.go
- partitioning/gpt/gpt_test.go
- partitioning/partioning_test.go
- partitioning/partitioning.go
Device wipe mostly copied from v1 library with some fixes.
Partition devname was in Talos PR, but it should be better here.
> feat: add device wipe and partition devname

- partitioning/gpt/gpt.go
There is subtle issue with return code 'EBUSY' while myEntry is nil, which might not fall through into this code to report an error correctly.
> fix: don't ignore error on partition delete
